// Generated by CoffeeScript 1.10.0
(function() {
	document.addEventListener('DOMContentLoaded', function() {
		var action, fn, hexaPhoto, i, j, len1, photoControls, ref, leftControl, rightControl;
		hexaPhoto = new HexaFlip(document.getElementById('slider-container'), {
			photos: ['a', 'b', 'c']
		}, {
			horizontalFlip: true
		});
		leftControl = document.getElementById('slider-control--left');
		rightControl = document.getElementById('slider-control--right');

		leftControl.addEventListener('click', (function() {
			return hexaPhoto['flipBack']();
		}), false);
		rightControl.addEventListener('click', (function() {
			return hexaPhoto['flip']();
		}), false);
	}, false);

}).call(this);

//# sourceMappingURL=demo.js.map
