// Generated by CoffeeScript 1.10.0
(function() {
	document.addEventListener('DOMContentLoaded', function() {
		var action, fn, hexaPhoto, i, j, len1, photoControls, ref;
		hexaPhoto = new HexaFlip(document.getElementById('photo-demo'), {
			photos: ['a', 'b', 'c', 'd', 'e', 'f']
		}, {
			size: 400,
			horizontalFlip: true
		});
		photoControls = document.getElementById('photo-controls');
		ref = ['flipBack', 'flip'];
		fn = function(action) {
			return photoControls.children[i].addEventListener('click', (function() {
				return hexaPhoto[action]();
			}), false);
		};
		for (i = j = 0, len1 = ref.length; j < len1; i = ++j) {
			action = ref[i];
			fn(action);
		}
	}, false);

}).call(this);

//# sourceMappingURL=demo.js.map
